Update rococo v1 to polakdot v0.9.1
substrate-developer-hub/substrate-parachain-template pull request #34
Opened 2021-05-23 17:34 UTC by samelamin

2021-05-23 21:52 UTC, NukeManDan requested changes
Thanks for this!! There are some things that need to be manually translated to keep this as a template, not a copy of cumulus. If you like, make some changes here to fix, but I intend to implement these myself anyhow to learn 😁 
LMK.

2021-05-23 21:52 UTC, NukeManDan commented on node/src/chain_spec.rs
> +				hex!["9ed7705e3c7da027ba0583a22a3212042f7e715d3c168ba14f1424e2bc111d00"].into(),
Why this? did you use a custom authority?

2021-05-23 21:52 UTC, NukeManDan commented on node/src/chain_spec.rs
> +			relay_chain: "westend-dev".into(),
This correct? you set rococo in the readme

2021-05-23 21:52 UTC, NukeManDan commented on node/src/chain_spec.rs
> +fn shell_testnet_genesis(parachain_id: ParaId) -> cumulus_shell_runtime::GenesisConfig {
not needed for the template AFAIK

2021-05-23 21:52 UTC, NukeManDan commented on node/src/cli.rs
> +// Copyright 2019-2021 Parity Technologies (UK) Ltd.
I think we intentionally include no licenec - the "unlicense" should cover this

2021-05-23 21:52 UTC, NukeManDan commented on node/src/cli.rs
>  	/// Default: 100
1000 now for non- system chains

2021-05-23 21:52 UTC, NukeManDan commented on node/src/cli.rs
> -	#[structopt(long, conflicts_with = "chain")]
why remove thew struct op? and the next too

2021-05-23 21:52 UTC, NukeManDan commented on node/src/cli.rs
> +structopt::clap::AppSettings::GlobalVersion,
nitpick - should include tab

2021-05-23 21:52 UTC, NukeManDan commented on node/src/command.rs
> +// Copyright 2019-2021 Parity Technologies (UK) Ltd.
rm licence

2021-05-23 21:52 UTC, NukeManDan commented on node/src/command.rs
> -	Ok(match id {
we want dev. Why change this? no staging or shell here in the template

2021-05-23 21:52 UTC, NukeManDan commented on node/src/command.rs
> -		"Parachain Collator Template".into()
keep this

2021-05-23 21:52 UTC, NukeManDan commented on node/src/command.rs
> -			"Parachain Collator Template\n\nThe command-line arguments provided first will be \
keep

2021-05-23 21:52 UTC, NukeManDan commented on node/src/command.rs
> -		"https://github.com/substrate-developer-hub/substrate-parachain-template/issues/new".into()
keep

2021-05-23 21:52 UTC, NukeManDan commented on node/src/command.rs
> +		load_spec(id, self.run.parachain_id.unwrap_or(100).into())
```suggestion
		load_spec(id, self.run.parachain_id.unwrap_or(1000).into())
```

2021-05-23 21:52 UTC, NukeManDan commented on node/src/command.rs
> -	fn native_runtime_version(_: &Box<dyn ChainSpec>) -> &'static RuntimeVersion {
keep

2021-05-23 21:52 UTC, NukeManDan commented on node/src/command.rs
> -	fn native_runtime_version(_: &Box<dyn ChainSpec>) -> &'static RuntimeVersion {
the rest of the file needs to remain for the template

2021-05-23 21:52 UTC, NukeManDan commented on runtime/Cargo.toml
> +pallet-assets = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.2" }
not used?

2021-05-23 21:52 UTC, NukeManDan commented on runtime/Cargo.toml
> +cumulus-ping = { git = 'https://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.2', default-features = false }
not used?

2021-05-23 21:52 UTC, NukeManDan commented on runtime/src/lib.rs
> +	pub const SS58Prefix: u8 = 0;
```suggestion
	pub const SS58Prefix: u8 = 42;
```
use the right one ;)

2021-05-23 21:54 UTC, samelamin commented
@NukeManDan no worries, I tried to keep it as close to cumulus to get it to build. I will work on these changes tomorrow, now that its built all these changes should be relatively simple to implement 👍

2021-05-24 03:32 UTC, NukeManDan commented
Thanks again for the PR! I think I got my PR working now, with the updates needed. 🙏🏼 
I am going to close this in favor of that for now.

2021-05-24 03:32 UTC, closed without merging