Updated to polkadot v0.9.7
substrate-developer-hub/substrate-parachain-template pull request #50
Opened 2021-07-01 12:12 UTC by jimmychu0807

- We should tag the polkadot version, similar to what's in the cumulus and polkadot, once this is merged
- Edited the README.md

2021-07-01 16:04 UTC, NukeManDan commented on runtime/src/lib.rs
> -
did you determine this is not needed? If so, why do we import it at all? https://github.com/substrate-developer-hub/substrate-parachain-template/pull/50/files#diff-6431a3eec6e102bbcffb94387cda89efbe02002649745273fb575234c0018de4R50

2021-07-01 16:38 UTC, NukeManDan requested changes
~Lets figure out #49 in this PR 🙏🏼 ~ we can address in new pr

2021-07-02 04:37 UTC, jimmychu0807 commented
The latest commit:

- Edited the README.md, added diagram (added on 21-07-02)
- Remove all default value of ParaId if not given in command.rs (added on 21-07-02)

2021-07-02 16:13 UTC, NukeManDan approved these changes

2021-07-02 16:14 UTC, merged